name: Auto Label
on:
  pull_request:
    types: [opened, push, synchronize]

jobs:
  auto-label:
    name: Auto Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 8BitJonny/gh-get-current-pr@1.0.1
        id: PR
        with:
          github-token: ${{ secrets.GEN3_RELEASE_GH_TOKEN }}
          filterOutClosed: true
      - run: echo "Your PR is ${prNumber} and its JSON is ${prJSON}"
        env:
          prNumber: ${{ steps.PR.outputs.number }}
          prJSON: ${{ steps.PR.outputs.pr }}
      - uses: banyan/auto-label@1.2
        env:
          GITHUB_TOKEN: "${{ contains(secrets, 'GEN3_RELEASE_GH_TOKEN') && secrets.GEN3_RELEASE_GH_TOKEN || 'ignore' }}"
          
