name: Auto Label
on:
  pull_request:
    types: [opened, push, synchronize]

jobs:
  auto-label:
    name: Auto Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 8BitJonny/gh-get-current-pr@1.0.1
        id: PR
        with:
          github-token: "${{ contains(secrets, 'GEN3_RELEASE_GH_TOKEN') && secrets.GEN3_RELEASE_GH_TOKEN || secrets.GITHUB_TOKEN }}"
          filterOutClosed: true
      - run: echo "whole output: ${wholeOutput} . Your PR is ${prNumber} and its JSON is ${prJSON}"
        env:
          prNumber: ${{ steps.PR.outputs.number }}
          prJSON: ${{ steps.PR.outputs.pr }}
          wholeOutput: ${{ steps.PR.outputs }}
      - uses: banyan/auto-label@1.2
        if: fromJson(steps.PR.outputs.pr).head.repo.full_name == 'uc-cdis/cdis-manifest'
        env:
          GITHUB_TOKEN: "${{ contains(secrets, 'GEN3_RELEASE_GH_TOKEN') && secrets.GEN3_RELEASE_GH_TOKEN || 'ignore' }}"
          
