name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: 8BitJonny/gh-get-current-pr@1.0.1
        id: PR
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          filterOutClosed: true
      - run: echo "Your PR is ${prNumber} and its JSON is ${prFullRepoName}"
        if: success() && steps.PR.outputs.number
        env:
          prNumber: ${{ steps.PR.outputs.number }}
          prFullRepoName: ${{ fromJson(steps.PR.outputs.pr).head.repo.full_name }}
      - name: automerge
        uses: "pascalgn/automerge-action@v0.13.1"
        if: fromJson(steps.PR.outputs.pr).head.repo.full_name == 'uc-cdis/cdis-manifest'
        env:
          GITHUB_TOKEN: "${{ contains(secrets, 'GEN3_RELEASE_GH_TOKEN') && secrets.GEN3_RELEASE_GH_TOKEN || 'ignore' }}"
