name: Auto Label
on:
  pull_request:
    types: [opened, push, synchronize]

jobs:
  auto-label:
    name: Auto Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get branch name based on PR
        uses: andrevalentin/get-branch-name-by-pr@1.0.0
        id: pr_data
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "Your PR ${PR}"
        env:
          PR: ${{ fromJson(steps.pr_data.outputs) }}
      - uses: banyan/auto-label@1.2
        env:
          GITHUB_TOKEN: "${{ contains(secrets, 'GEN3_RELEASE_GH_TOKEN') && secrets.GEN3_RELEASE_GH_TOKEN || 'ignore' }}"
          
